### ISSUE TITLE
Document how unix-daemonize interacts with threads

### ISSUE THREAD

**Issue by droundy** [swizard0/unix-daemonize#1]
I would like to know how unix-daemonize interacts with threads.  Specifically, can I call `daemonize_redirect` in a thread in order to spawn a daemon?

**Comment by swizard0** [comment]
Technically you can. But remember the fact that [std::process:exit](https://doc.rust-lang.org/std/process/fn.exit.html) is [invoked](https://github.com/swizard0/unix-daemonize/blob/master/src/lib.rs#L91) for parent process after `fork`. So just keep in mind the words about destructors from `std::process::exit` docs when you want to daemonize from a thread.
