### ISSUE TITLE
leave existing process?

### ISSUE THREAD

**Issue by droundy** [swizard0/unix-daemonize#2]
Would it be possible to have an option to leave the spawning process running, so I could spawn a daemon and then do something else?

**Comment by swizard0** [comment]
AFAIK "to spawn a daemon" in unix actually means that the parent process has to exit, or there could be problems with detaching from a terminal or something like zombies left.

Maybe it will be enough for you just to spawn a thread or another "fork" right after daemonizing?

**Comment by droundy** [comment]
I see. I think the solution for me will simply to start the daemon last then. Thanks for the explanation!
